define({
  // General
  "tableFields": "taulukon kentät",
  "seeAll": "näytä kaikki",
  "noLimit": "ei rajausta",
  "notExist": "ei löydy",
  "exist": "löytyy",
  "digital": "digi",
  "print": "printti",
  "close": "sulje",
  "startOver": "aloita alusta",
  "edit": "muokkaa",
  "remove": "poista",
  "cancel": "peruuta",
  "duplicate": "monista",
  "save": "tallenna",
  "select": "valitse",
  "confirm": "vahvista",
  "or": "tai",
  "until": "asti",
  "customer": "asiakas",
  "package": "paketti",
  "offers": "tarjoukset",
  "yes": "kyllä",
  "no": "ei",
  "months": "kk",
  "days": "pv",
  "listing": "listaus",
  "basicInfo": "perustiedot",
  "extraInfo": "lisätiedot",
  "noResult": "ei löytynyt",
  "resetFilter": "tyhjennä valinnat",
  "resetForm": "tyhjennä",
  "invalidFields": "Tarkasta puuttuvat tai väärin täytetyt kentät",
  "unknownError": "Tuntematon virhe. Ota yhteyttä ylläpitoon.",
  "week": "Viikko",
  "show": "näytä", 
  "and": "ja", 
  "pc": "kpl", 
  "users": "käyttäjät",
  "userManagement": "käyttäjähallinta",
  "warning": "varoitus",
  "all": "kaikki",
  "passwordSent": "Salasana lähetetty käyttäjälle",
  "passwordFail": "Salasanan vaihto epäonnistui",
  "passwordSuccess": "Salasana vaihdettu onnistuneesti",
  "orderPriceUpdateSuccess": "Tilauksen hinta päivitetty onnistuneesti",
  "orderPriceUpdateFail": "Tilauksen hinnan päivitys epäonnistui",

  // Login
  "loginWelcome": "Tervetuloa",
  "loginInstruction": "Kirjaudu sisään hallinta- tai asiakaspalvelutunnuksillasi jatkaaksesi eteenpäin.",
  "loginUser": "käyttäjätunnus",
  "loginPassword": "salasana",
  "loginSubmit": "kirjaudu",
  "loginFailed": "Kirjautuminen epäonnistui",
  "loginFailedInstructions": "Tarkista käyttäjätunnus ja salasana.",

  // Home
  "salesSystem": "MyDigi",
  "logout": "kirjaudu ulos",
  "hidemenu": "näytä/piilota valikko",
  "customers": "asiakkaat",
  "orders": "tilaukset",
  "products": "tuotteet",
  "packages": "paketit",
  "administration": "ylläpito",
  "packageCalendar": "myyntikalenteri",
  "settings": "hallinta",
  "landingPages": "myyntipaikat",
  "analytics": "analytiikka",
  "analyticsSubscribers": "tilaajat",
  "analyticsSales": "uusmyynti",
  "analyticsContinuals": "kestotilaajat",
  "resetPassword": "lähetä uusi salasana",

  // Profile
  "profileInfo": "käyttäjätiedot",
  "userID": "ID",
  "userEmail": "sähköpostiosoite",
  "userFirstName": "etunimi",
  "userLastName": "sukunimi",
  "oldPassword": "nykyinen salasana",
  "newPassword": "uusi salasana",
  "confirmPassword": "vahvista salasana",
  "changePassword": "vaihda salasana",
  "passwordChangeFailed": "Salasanan muutos ei onnistunut",
  "newPasswordMissing": "Uusi salana puuttuu",
  "newPasswordMismatch": "Salasanat eivät vastaa toisiaan",
  "wrongPassword": "Väärä salasana",
  "passwordChangeSuccess": "Salasana muutettu onnistuneesti",
  "passwordChangeSuccessDescription": "Salasana käyttäjälle _EMAIL_ on vaihdettu",
  "userLekaUserID": "Leka-tunnus",
  "userLekaSalesID": "Myyjätunnus",
  "changeLekaInfo": "Tallenna Leka-tunnukset",
  "lekaInfoUpdateFailed": "Leka-tunnusten päivittäminen epäonnistui",
  "lekaInfoMissing": "Syötä tunnus tai myyjätunnus",
  "lekaInfoUpdateSuccess": "Leka-tunnusten päivittäminen onnistui",
  "lekaInfoUpdateSuccessDescription": "Leka-tunnukset käyttäjälle _EMAIL_ on päivitetty.",
  "currentPasswordMissing": "Syötä nykyinen salasanasi.",
  "requiredField": "Pakollinen kenttä.",

  // DataTable
  "sSortAscending": "lajittele nousevasti",
  "sSortDescending": "lajittele laskevasti",
  "sFirst": "<i class='fa fa-lg fa-angle-double-left'></i>",
  "sLast": "<i class='fa fa-lg fa-angle-double-right'></i>",
  "sNext": "<i class='fa fa-lg fa-angle-right'></i>",
  "sPrevious": "<i class='fa fa-lg fa-angle-left'></i>",
  "sEmptyTable": "ei yhtään osumaa",
  "sInfo": "näytetään _START_ - _END_ riviä _TOTAL_:stä rivistä",
  "sInfoEmpty": "ei yhtään osumaa",
  "sInfoFiltered": "suodatettu _MAX_ tuloksesta",
  "sInfoPostFix": "",
  "sInfoThousands": "",
  "sLengthMenu": "näytä _MENU_ osumaa",
  "sLoadingRecords": "ladataan tuloksia",
  "sProcessing": "ladataan",
  "sSearch": "hae",
  "sUrl": "",
  "sZeroRecords": "ei yhtään osumaa",

  // Customers view
  "newCustomer": "uusi asiakas",
  "addCustomer": "lisää asiakas",
  "customerID": "ID",
  "customerName": "nimi",
  "customerNumber": "asiakasnumero",
  "customerEmail": "sähköpostiosoite",
  "customerAccountCreated": "tili tehty",
  "customerLastLogin": "viimeisin kirjautuminen",
  "customerLastActive": "viimeksi aktiivinen",
  "customerDetails": "asiakas",
  "customerContact": "yhteystiedot",
  "customerOrders": "tilaukset",
  "orderCancelConfirmationAlt": "Oletko varma, että haluat peruuttaa tilauksen <b>_ORDER_ID_</b> asiakkaalta <i>_CUSTOMER_</i>?",

  // Customer dialog
  "userInfo": "käyttäjän tiedot",
  "customerUserID": "käyttäjän ID",
  "userCreated": "luotu",
  "moreInfo": "lisätiedot",
  "lekaCustomerNumber": "leka asiakasnumero",
  "customerPhoneMarketable": "salli puhelinmarkkinointi",
  "customerEmailMarketable": "salli sähköpostimarkkinointi",
  "customerContactInfo": "yhteystieto",
  "addContact": "lisää yhteystieto",
  "contactDeleteConfirmation": "Haluatko varmasti poistaa yhteystiedon <i>_CONTACT_</i>?",
  "customerEmailUsed": "Sähköpostiosoite on jo käytössä toisessa tilissä.",
  "deleteContact": "Poista yhteystieto",
  "contactAddFailed": "Yhteystiedon lisäys epäonnistui",
  "contactDeleteFailed": "Yhteystiedon poisto epäonnistui",
  "contactUpdateFailed": "Yhteystiedon päivitys epäonnistui",
  "customerAddFailed": "Asiakkaan lisäys epäonnistui",
  "emailChangeFailed": "Sähköpostin vaihto epäonnistui",
  "customerAddSuccess": "Asiakkaan lisäys onnistui",
  "customerAddSuccessDescription": "Asiakas _EMAIL_ lisätty onnistuneesti",
  "customerServiceAccess": "Palveluiden käyttö",
  "serviceURL": "Palvelun osoite",
  "lastAuth": "Viimeisin kirjautuminen",
  "firstAuth": "Ensimmäinen kirjautuminen",

  // Invoices

  "invoiceInvoiceInstructionNumber": "Laskuohjenumero",
  "invoiceReferenceDate": "Laskun päiväys",
  "invoiceCurrencyCode": "Valuuttaviitteen valuuttakoodi",
  "invoiceDueDate": "Eräpäivä",
  "invoiceProductCode": "Tuote",
  "invoiceBatchNumber": "Erä",
  "invoiceOrderDeliveryStartDate": "Tilauksen 1 toimituspvm",
  "invoiceOrderEndDate": "Tilauksen päättymispvm",
  "invoiceRate": "Valuuttakurssi",
  "invoiceReferenceNumber": "Viitenumero ilman tarkistenumeroita",
  "invoiceExpenseAllocationOrder": "Suorituksen kohdistus",
  "invoiceExpenseType": "Huomautuskulu",
  "invoiceExpense": "Kulu",
  "invoiceExpenseVat": "Kulun arvonlisävero",
  "invoiceExpenseTotal": "Kulu yhteensä (laskulla)",
  "invoiceExpensePayment": "Kulu maksettu",
  "invoiceExpenseVatPayment": "Kulun alvia maksettu",
  "invoiceExpenseTotalPayment": "Kulua yhteensä maksettu",
  "invoiceInExpenseAllocation": "Otetaan mukaan suoritukseen",
  "invoiceExpenseCurrencyCode": "Kulun valuuttakoodi",
  "invoiceWvType": "Laskutyyppi",
  "invoiceInvoiceAddress": "Verkkolaskuosoite",
  "invoiceType": "Laskun tyyppi",
  "invoicePacketReferenceNumber": "Pakettilaskun pääviitenumero", 
  "invoiceReference": "Viitenumero",
  "invoiceVtype": "Laskutyyppi",
  "invoiceSmin": "Maksettava vähintään tilausmaksua",
  "invoiceSmax": "Maksimisuoritus",
  "invoiceVmin": "Minimisuoritus",
  "invoiceSiscount": "?",
  "invoiceAdiscount": "?",
  "invoiceAmin": "?",
  "invoiceAmax": "?",

  // Payments

  "paymentAmount": "Summa",
  "paymentarchiveNumber": "Arkistointitunnus",
  "paymentCorrectionIdentifier": "Oikaisutunnus",
  "paymentCurrencyCode": "Valuuttakoodi",
  "paymentInvoiceInstructionNumber": "Laskuohjenumero",
  "paymentLoggingAccountNumber": "Kirjaustili",
  "paymentLoggingDate": "Pankkipäivä",
  "paymentDate": "Maksupäivä",
  "paymentNumber": "Suoritusnumero",
  "paymentType": "Suorituksen tyyppi",
  "paymentRecipientAccountNumber": "Maksajan nimi",
  "paymentReference": "Viitenumero",
  "paymentReferenceNumber":"Viitenumero",
  "paymentTransactionDate": "Kirjauspäivä",
  "paymentWCorrectionIdentifier": "Oikaisutunnus",


  // Contact dialog
  "contactMissingMandatoryField": "Yhteystietoja ei tallennettu vaadittujen kenttien puuttumisen takia.",

  // Orders view
  "orderCreated": "tilaus tehty",
  "orderLastPaid": "viimeisin maksu",
  "orderStatus": "tila",
  "inactive": "maksamaton",
  "active": "aktiivinen",
  "suspended": "keskeytetty",
  "cancel_pending": "peruutettavana",
  "cancel_delayed": "peruttu tarjousjakson loppuun",
  "renewal_pending": "odottaa uusimista",
  "cancelled": "peruutettu",
  "auto_cancelled": "peruutettu",
  "finished": "päättynyt",
  "orderID": "ID",
  "orderCustomerName": "asiakas",
  "orderDetails": "tilaus",
  "orderPayments": "maksut",
  "createOrder": "luo tilaus",

  // Order dialog
  "order": "tilaus",
  "newOrder": "uusi tilaus",
  "orderOffers": "sisältö",
  "sendConfirmationEmail": "lähetä tilausvahvistus",
  "sendConfirmationEmailMandatory": "Maksuvahvistus on pakollinen korttitilauksille",
  "deliveryInfo": "toimitustiedot",
  "customerFirstName": "etunimi",
  "customerLastName": "sukunimi",
  "customerPhone": "puhelin",
  "customerMobile": "mobiili",
  "customerAddress": "osoite",
  "customerPostalCode": "postinumero",
  "customerCity": "kaupunki",
  "customerCountry": "maa",
  "customerCompany": "yritys",
  "orderInfo": "tilauksen tiedot",
  "orderID": "tilaus ID",
  "orderPaymentTime": "maksuaika",
  "orderPaymentMethod": "maksutapa",
  "orderSoldByService": "myyntikanava",
  "orderSoldByUser": "myyjä",
  "cancelOrder": "peruuta tilaus",
  "selectOffers": "tee valinnat",
  "orderCancelConfirmation": "Oletko varma, että haluat peruuttaa tämän tilauksen?",
  "billTime": "aika",
  "billPrice": "hinta",
  "billTaxPercent": "veroprosentti",
  "billAttemptTime": "yritetty",
  "billStatus": "tila",
  "selectCustomer": "valitse asiakas",
  "selectPackage": "valitse paketti",
  "pending": "avoin",
  "paid": "maksettu",
  "error": "virhe",
  "failed": "epäonnistunut",
  "packageProductFilter": "hakuehdot",
  "processing": "käsittelyssä",
  "showPackage": "näytä",
  "orderCreateSuccess": "Tilaus luotu onnistuneesti",
  "orderCreateSuccessDescription": "Tilaus luotu onnistuneesti käyttäjälle _EMAIL_",
  "orderCreateFailed": "Tilauksen luonti epäonnistui",
  "orderMissingOffer": "Valitse vähintään yksi tarjous",
  "orderCancelFailed": "Tilauksen peruuttaminen epäonnistui",
  "orderCancelSuccess": "Tilauksen peruuttaminen onnistui",
  "orderCheckFailed": "Tilausta ei voida luoda",
  "orderCheckFailedLimit": "Tilauksen hinta ylittää maksurajan",
  "orderCheckFailedCreditPrice": "Tilausta ei voi maksaa maksukortilla",
  "orderSelectPackgeFirst": "Valitse ensin tilauspaketti",

  // Order cancel confirm dialog
  "orderCancelSource": "peruutuskanava",
  "orderCancelReason": "peruutuksen syy",
  "cancelSourceCustomerPhone": "asiakkaalta puhelimitse",
  "cancelSourceCustomerFax": "asiakkaalta faksitse",
  "cancelSourceCustomerLetter": "asiakkaalta kirjeitse",
  "cancelSourceCustomerEmail": "Asiakkaalta sähköpostitse",
  "cancelSourceCustomerInternet": "Asiakkaalta netin kautta",
  "cancelSourceMagazineCancel": "lehti keskeytys",
  "cancelSourceMagazineStop": "lehti lopetettu",
  "cancelSourcePaymentProblem": "maksuhäiriö",
  "cancelSourceSellerFax": "myyjältä faksitse",
  "cancelSourceSellerLetter": "myyjältä kirjeitse",
  "cancelSourceSellerPhone": "myyjältä puhelimitse",
  "cancelSourceSellerEmail": "myyjältä sähköpostitse",
  "cancelSourceSellerCannon": "myyjältä tykillä",
  "cancelSourceServiceAutomat": "palveluautomaatilta",
  "cancelSourceServiceCard": "palvelukortilla",
  "cancelSourcePostalReturn": "postin palautus",
  "cancelSourceOutOfProduct" : "tuote loppu",
  "cancelSourceTechnicalCancel": "tekninen peruutus",
  "cancelSourceSellerVictory": "myyjältä Voitolla",
  "cancelSourceUndefined": "-- tyhjä valinta --",
  "cancelReasonUnknown": "ei tiedossa",
  "cancelReasonDidNotOrder": "ei ole tilannut",
  "cancelReasonDead": "kuollut",
  "cancelReasonOld": "sairaus, vanhuus",
  "cancelReasonDoubleOrder": "kaksoistilaus",
  "cancelReasonServiceAutomat" : "palveluautomaatin peruutus",
  "cancelReasonPaymentDifficulties": "maksuvaikeudet",
  "cancelReasonOtherReason": "muu syy",
  "cancelReasonPostalReturn": "postin palautus, osoite tuntematon",
  "cancelReasonMagazineChange": "lehden vaihto/lopetus",
  "cancelReasonUndefined": "-- tyhjä valinta --",
  "cancelReasonCancelRejection": "Peruutuksen torjunta",

  "orderCancellationText": "Peruutus",
  // Products view
  "productSalesStart": "myynti alkaa",
  "productSalesEnd": "myynti loppuu",
  "productStatus": "tila",
  "productStatusForSale": "myynnissä",
  "productStatusNotForSale": "ei myynnissä",
  "productID": "ID",
  "productGroup": "tuoteryhmä",
  "productTitle": "nimi",
  "productType": "tyyppi",
  "productRevision": "versio",
  "productPrice": "hinta",
  "productDetails": "tuote",
  "productOffers": "tarjoukset",

  // Product dialog
  "newProduct": "uusi tuote",
  "productCode": "tuotetunnus",
  "productShortCode": "tuotetunnus",
  "productAddressCollection": "OT",
  "productDescription": "kuvaus",
  "productOrderType": "tilaustyyppi",
  "productFixedSales": "määräaikainen",
  "productOpenSales": "kestotilaus",
  "repeating": "kesto",
  "productRecurrentSales": "toistuvaismaksu",
  "productDuration": "kesto",
  "productSalesTime": "myyntiaika",
  "productOnSale": "myynnissä",
  "productCreated": "luontiaika",
  "productPaymentType" : "maksutapa",
  "productOstno": "ostonumero",
  "createOffer": "luo tarjous",
  "addNewVersion": "luo uusi versio",
  "productExtraDescription": "lisäkuvaus",
  "productReceiptInfo": "kuittitieto",
  "priceDefinitions": "korttimaksuhinnastot",
  "addPriceDefinition": "lisää hinnasto",
  "addPrices": "lisää hintatiedot",
  "priceDefinitionName": "hinnaston nimi",
  "priceDefinitionDescription": "kuvaus",
  "priceDefinitionDate": "hinnaston voimaantulopäiväys",
  "priceDefinitionPrices": "hinnasto",
  "newPriceDefinition": "uusi hinnasto",
  "productAddSuccess": "Tuotteen lisäys onnistui",
  "productAddSuccessDescription": "Tuote _NAME_ lisätty onnistuneesti",
  "productAddFailed": "Tuotteen lisäys epäonnistui",
  "productUpdateSuccess": "Tuotteen päivitys onnistui",
  "productUpdateSuccessDescription": "Tuote _NAME_ päivitetty onnistuneesti",
  "productUpdateFailed": "Tuotteen päivitys epäonnistui",
  "productDeleteFailed": "Tuotteen poisto epäonnistui",
  "productInvalidShortCode": "Tuotetunnus tulee olla kaksi merkkiä",
  "productInvalidPriceDefs": "Hinnastossa ei saa olla tyhjiä kenttiä",
  "productDeleteConfirmation": "Oletko varma, että haluat poistaa tuotteen _NAME_?",
  "productInvalidDescription": "Kuvaus on pakollinen ja sen pitää olla 5-52 merkkiä pitkä",
  "productTexts": "Tilaustietojen tekstit",
  "productTextsExplanation": "Tekstit tilaustietojen yhteyteen riippuen muista saman tuoteryhmän tilauksista. Toinen tuotetyyppi on digi, mikäli katseltava tuote on printti ja päinvastoin",
  "productInfoText": "Tekstit tilaustietojen yhteyteen riippuen muista saman tuoteryhmän tilauksista. Toinen tuotetyyppi on digi, mikäli katseltava tuote on printti ja päinvastoin",
  "fixedSiblingRenewing": "Määräaikaisen tilauksen lisäksi saman tuoteryhmän toinen tuotetyyppi kestotilauksena",
  "renewingSiblingRenewing": "Kestotilauksen lisäksi saman tuoteryhmän toinen tuotetyyppi kestotilauksena",
  "fixedSiblingFixed": "Määräaikaisen tilauksen lisäksi saman tuoteryhmän toinen tuotetyyppi määräaikaisena",
  "renewingSiblingFixed": "Kestotilauksen lisäksi saman tuoteryhmän toinen tuotetyyppi määräaikaisena",
  "fixedSiblingNone": "Määräaikaisen tilauksen lisäksi ei saman tuoteryhmän toista tuotetta",
  "renewingSiblingNone": "Kestotilauksen lisäksi ei saman tuoteryhmän toista tuotetta",

  // Offer dialog
  "offer": "tarjous",
  "newOffer": "uusi tarjous",
  "offerName": "nimi",
  "offerFixedPrice": "hinta",
  "offerPricePercentage": "hinnanmuutos",
  "offerDuration": "kesto",
  "offerSalesTime": "myyntiaika",
  "offerPaymentType" : "maksutapa",
  "fixed": "määräaikainen",
  "renewing": "kestotilaus",
  "recurring": "toistuvaismaksu",
  "repeating": "kesto",
  "offerExtraDescription": "lisäkuvaus",
  "offerReceiptInfo": "kuittitieto",
  "cardPayment": "korttimaksu",
  "paperPayment": "lasku",
  "durationOfferRow": "kesto",
  "fixedOfferDateRow": "määräaikainen (pvm)",
  "fixedOfferPeriodRow": "määräaikainen (kk)",
  "fixedOfferStartEndDate": "määräaikainen (päivämääräperustainen)",
  "offerPeriodBeginning": "alkaen",
  "offerPeriodTill": "asti",
  "lekaRequirements": "Lisävaatimukset",
  "lekaRequirementAllAccepted": "kaikki hyväksytty",
  "offerDurationTypeDays": "Päivämääräperustainen",
  "offerDurationTypeMonths": "Kuukausittainen",

  // Packages view
  "packageSalesStart": "myynti alkaa",
  "packageSalesEnd": "myynti loppuu",
  "packageDurationSource": "kesto",
  "packageDurationByProducts": "tuotteittain",
  "packageDurationByOffers": "tarjouksittain",
  "packageDurationByPackage": "paketti",
  "packageSalesTime": "myyntiaika",
  "packageID": "ID",
  "packageName": "nimi",
  "packageDescription": "kuvaus",
  "packageDuration": "kesto",
  "addPackage": "lisää paketti",

  "invoiceInformation": "Laskutustiedot",
  "payments": "Suoritukset",

  // Package dialog
  "package": "paketti",
  "newPackage": "uusi paketti",
  "packageDetails": "paketti",
  "packageOffers": "tarjoukset",
  "packageRules": "säännöt",
  "packageAddressCollection": "osoitteistonumero",
  "packageMarketingName": "markkinointinimi",
  "packageNormalPrice": "normaalihinta",
  "packageMarketingPrice": "paketin markkinointihinta",
  "packageMarketingSubtext": "paketin alateksti",
  "packageExtraDescription": "paketin lisäkuvaus",
  "packageDiscountCode": "Tilaajaetukoodi",
  "selectProduct": "valitse tuote",
  "giveAways": "Kylkiäiset",
  "totalCost": "yhteensä",
  "billingPeriod": "Kestotilauksen veloituskausi",
  "offerPeriods": "tarjousjaksot",
  "billPeriod": "laskutusjakso",
  "offerAlways": "aina",
  "salesChannels": "myyntipaikat",
  "selectSalesChannel": "valitse myyntikanava",
  "offerName": "nimi",
  "offerPrice": "hinta",
  "offerDiscount": "alennus%",
  "offerStart": "alkaen",
  "offerEnd": "päättyen",
  "offerAddressCollection": "OT",
  "product": "tuote",
  "addOffer": "lisää tarjous",
  "addSelection": "lisää valinta",
  "addCondition": "lisää ehto",
  "secretOrderPrice": "Hinta",
  "offerAddFailed": "Tarjouksen lisäys ei onnistu",
  "lueKirjaPaperPriceFail": "Luekirja-tuotteille ei voi asettaa hintaa laskulle",
  "offerAddNormalLuekirjaFail": "Luekirjaa ei voi paketoida muiden tuotteiden kanssa",
  "offerRemoveConfirmation": "Oletko varma, että haluat poistaa tämän tarjouksen?",
  "giveAwayLueKirjaFail": "Kylkiäistä ei voi lisätä Luekirjaan",
  "lueKirjaFreePriceFail": "Ilmaispaketin hinta pitää olla 0",
  "lueKirjaFreeCardFail": "Ilmaispaketilla ei voi olla luottokorttihintaa",
  "fragmentedOrderErrorMessage": "Tilauksen teko onnistui MyDigiin, mutta Leka-käsittelyssä virhe. Tarkista virhelista",
  "subpackageNotPossibleInLuekirja": "Kylkiäinen ei voi olla Luekirja-tuote",
  "removeOffer": "poista tarjous",
  "serviceName": "palvelun nimi",
  "servicePointName": "palvelupiste",
  "servicePointURL": "osoite",
  "openServicePoint": "avaa",
  "salesReturnPage": "myynnin jälkeinen siirto",
  "servicesOwn": "pysy tilaussivulla",
  "packageAddSuccess": "Paketin lisäys onnistui",
  "packageAddSuccessDescription": "Paketti _NAME_ lisätty onnistuneesti",
  "packageAddFailed": "Paketin lisäys epäonnistui",
  "packageUpdateSuccess": "Paketin päivitys onnistui",
  "packageImageUpdateSuccess": "Paketin kuvan päivitys onnistui",
  "packageUpdateSuccessDescription": "Paketti _NAME_ päivitetty onnistuneesti",
  "packageUpdateFailed": "Paketin päivitys epäonnistui",
  "packageDeleteFailed": "Paketin poisto epäonnistui",
  "packageMissingOffer": "Paketissa ei ole yhtään tarjousta",
  "packageOfferPriceInconsistency": "Hintojen täytössä puutteita. Mikäli täytät yhden hinnan jommalle kummalle maksupuolelle, tulee jokaisella saman maksupuolen tarjousrivillä olla syötetty hinta.",
  "packageDeleteConfirmation": "Oletko varma, että haluat poistaa paketin _NAME_?",
  "packageImage": "paketin kuva",
  "s3error": "pakettitietojen päivitys Amazoniin epäonnistui",
  "initialsales": "uusmyynti",
  "continualsales": "jatkopaketti",
  "subpackage": "kylkiäispaketti",
  "subpackageOffersTooMany": "Kylkiäispaketissa voi olla vain yksi tarjous",
  "subpackageNotFixed": "Kylkiäispaketin tarvitsee olla määräaikainen",
  "subpackagePriceNotValid": "Kylkiäispaketin hinta täytyy olla 0",
  "packageCategory": "Paketin kategoria",
  "packageIsOrderPrevention": "Sisällytä peruutuksentorjuntaan",

  // Settings view
  "settingsUsers": "käyttäjät",
  "settingsVAT": "arvonlisävero",
  "settingsEvents": "tapahtumat",
  "userAccountCreated": "tunnus tehy",
  "userLastLogin": "viimeisin kirjautuminen",
  "userLevel": "käyttäjätaso",
  "customerservice": "asiakaspalvelu",
  "financialAdministration": "taloushallinto",
  "administrators": "pääkäyttäjä",
  "userName": "nimi",
  "vatRegion": "alue",
  "vatCountry": "maa",
  "eventTime": "tapahtuman aikarajaus",
  "eventType": "tapahtuman tyyppi",
  "eventOrder": "tilaus",
  "eventPayment": "maksu",
  "eventDataChange": "tietojen muutos",
  "eventID": "ID",
  "eventTime": "aika",
  "event": "tapahtuma",
  "eventUser": "käyttäjä",

  "invoice1": "Lasku ja kiinn.kysely",
  "invoice2": "Enn.ilm. ja kiinn.kysely",
  "invoice3": "Kesto/tilaajaetuliite lasku", 
  "invoice4": "Kesto/tilaajaetuliite enn.ilm.",
  "invoice5": "Sarjamarkkinointiliite lasku",
  "invoice6": "Sarjamarkkinointiliite enn.ilm.",
  "invoice7": "Tervetuloaliite lasku",
  "invoice8": "Tervetuloaliite enn.ilm.",
  "invoiceA": "Lasku",
  "invoiceB": "Uusi lasku, ei toimitusta",
  "invoiceC": "Sähköpostilasku",
  "invoiceE": "Ennakkoilmoitus",
  "invoiceF": "Kestot/lahjalehti ennakkoilmoitus",
  "invoiceG": "Maksettu verkossa",
  "invoiceH": "2.muistutus",
  "invoiceI": "Kestot/lahjalehti lasku",
  "invoiceJ": "Keskeytys (velkaa ei)",
  "invoiceK": "Keskeytys (velkaa on)",
  "invoiceL": "Lasku lähetetyistä lehd.",
  "invoiceM": "Muistutus",
  "invoiceN": "3.muistutus",
  "invoiceO": "Yksittäistuotteen lasku",
  "invoiceP": "2.lasku läh.lehd.(ulkom.)",
  "invoiceQ": "Yksittäistuote postiennakolla.",
  "invoiceR": "Tarjouslasku",
  "invoiceS": "Kestokäännytys",
  "invoiceT": "Tarjouslasku (uusi lomake)",
  "invoiceU": "Ulkop.perintä",
  "invoiceV": "Kestovaihtoehtolasku",
  "invoiceW": "Valtakirjalasku",
  "invoiceX": "Perintä 1",
  "invoiceY": "Perintä 2",
  "invoiceZ": "Perintä 3",

  "invoices": "Laskut",
  "payments": "Suoritukset",
  // User management
  "user": "käyttäjä",
  "newUser": "uusi käyttäjä",
  "userGivenName": "etunimi",
  "userFamilyName": "sukunimi",
  "basic": "asiakaspalvelu",
  "limited": "konepelti",
  "extended": "laajennettu",
  "administrative": "pääkäyttäjä",
  "userCreationSuccesful": "Käyttäjän luominen onnistui",
  "userCreationFailed": "Käyttäjän luominen epäonnistui",
  "userUpdateSuccesful": "Käyttäjän päivittäminen onnistui",
  "userUpdateFailed": "Käyttäjän päivittäminen epäonnistui",
  "userUpdateNoAction": "Käyttäjää ei päivitetty",
  "userDataSetUnchanged": "Tietoja ei ole muutettu",
  "userEmailUsed": "Sähköpostiosoite on jo käytössä",
  "userCreationSuccesfulMessage": "Käyttäjä _EMAIL_ on luotu",
  "userEmailEmpty": "Sähköpostiosoite ei saa olla tyhjä",
  "userDeleteSuccess": "Käyttäjän poisto onnistui",
  "userDeleteSuccessMessage": "Käyttäjä _EMAIL_ on poistettu",
  "userDeleteConfirmation": "Haluatko varmasti poistaa käyttäjän _EMAIL_?",
  "userDeleteFailed": "Käyttäjän poisto epäonnistui",
  "userHasSales": "Käyttäjällä on myyntejä",

  // Status message control
  "statusControl": "Palvelun tila",
  // Landingpagewidget
  "servicePointDataDirty": "Olet tehnyt muutoksia myyntipaikkaan. Haluatko silti avata pakettinäkymän? Pakettinäkymän tallentamisen yhteydessä myyntipaikan tiedot ladataan uudelleen ja tekemäsi muutokset menetetään.",

  // Analytics views
  "analyticsSettings": "asetukset",
  "visualizationTitle" : "visualisaatioasetukset",
  "dataTimeTitle" : "data ajalta",
  "days" : "päivää",
  "timeScale" : "ajanjakso",
  "timeTypeSelect" : "ryhmitys",
  "cancels": "peruutukset",
  "totals": "yhteensä",
  "productGroup" : "tuoteryhmä",
  "productCombo" : "tuoteryhmän paketti",
  "startDate" : "alkamispäivä",
  "endDate" : "päättymispäivä",
  "dataToVisualize" : "visualisoitava data",
  "selectGraphTypeTitle" : "valitse graafin tyyppi",
  "lineChart" : "viiva",
  "barChart" : "palkki",
  "pieChart" : "sektori",
  "graphExtraOptions" : "graafin lisävalinnat",
  "dataPoints" : "datapisteet",
  "shadows" : "varjot",
  "tooltip" : "lisätietokenttä",
  "plotGraph" : "luo graafi",
  "graph" : "graafi",
  "totalOrderCount" : "Tilauksia yhteensä",
  "totalSalesSum" : "Kokonaismyynti",
  "salesLabel" : "Myynnit",
  "ordersLabel" : "Tilaukset",
  "graphOrders" : "Kaikki tilaukset",
  "packageGraphOrders": "Tilaukset",
  "packageGraphSales": "Myynti",
  "continualSubscribers": "kestotilaajat",
  "cancellations": "Peruutukset",
  "analyticsPackage": "Paketti",
  "total": "yhteensä",
  "allOrders": "kaikki tilaukset",
  "yearView": "vuosinäkymä",
  "monthView": "kuukausinäkymä",
  "weekView": "viikkonäkymä",
  "dayView": "päivänäkymä",
  "diffValues": 'Näytä vertailuarvot ajanjaksolta',


  "orderRevival": "Voimaannosto",
  "orderPause": "Keskeytys",
  "orderPauseCommit": "Keskeytä tilaus",
  "orderTransfer": "Siirto",
  "orderRevivalCommit": "Voimaannosta tilaus",
  "orderTransferReceiver": "Saajan asiakasnumero",
  "orderTransferCommit": "Siirrä tilaus",
  "orderTransferFailed": "Tilauksen siirto epäonnistui",
  "ordeResumeSuccess": "Tilauksen voimaannosto onnistui",
  "orderTransferSuccess": "Tilauksen siirto onnistui",
  "orderBreakSuccess": "Tilauksen keskeytys onnistui",
  "orderBreakFailure": "Tilauksen keskeytys epäonnistui",
  "orderBreakMissingDates": "Täytä puuttuvat päivämäärät",

  "orderPauseStart": "Keskeytyksen alkupäivämäärä",
  "orderPauseEnd": "Keskeytyksen loppupäivämäärä",

  // Servicebreak
  "serviceBreakSettings": "Katkon asetukset",
  "serviceBreakEnvironment": "ympäristö",
  "environmentDev": "kehitys",
  "environmentProd": "tuotanto",
  "noUpcomingServiceBreaks": "Ei tulevia palvelukatkoja",
  "scheduledServiceBreak": "Palvelukatko on ajastettu",
  "ongoingServiceBreak": "Palvelukatko on käynnissä",
  "serviceBreakInvalidTiming": "Tarkista palvelukatkon ajankohta",
  "serviceBreakInvalidTimingMsg": "Aloitusaika ei voi olla myöhemmin kuin päättymisaika.",
  "serviceBreakSet": "Palvelukatko asetettu",
  "serviceBreakSetSuccess": "Palvelukatkon ajastus onnistui",

  // Konepelti 
  "widgetCustomerNumber": "Asiakasnumero",
  "widgetCustomerName": "Nimi",
  "widgetCustomerAddress": "Osoite",
  "widgetCustomerPOandCity": "Postinumero ja kaupunki",
  "widgetPostOffice": "Postinumero",
  "widgetEmail": "Sähköposti",
  "widgetSpecifier": "Tarkenne",
  "widgetPhone": "Puhelin",
  "widgetGenderUnknown": "Ei tiedossa",
  "widgetGenderF": "Yritys",
  "widgetGenderM": "Mies",
  "widgetGenderN": "Nainen",
  "widgetGenderX": "Ei tiedossa",
  "widgetGenderY": "Yhdistelmä",
  "widgetGender": "Sukupuoli",

  "widgetActive": "Voimassaolo",
  "widgetCountry": "Maa",

  "widgetProduct": "Tuote",
  "widgetDate": "Päivämäärä",
  "widgetOT": "OT",
  "widgetPrice": "Hinta",
  "widgetOfferNo": "Tarjousnumero",
  "widgetExplanation": "Selitys",
  "stompConfiguration": "Puhelinjärjestelmä",

  "widgetSeason": "Tilausjakso",

  "widgetPayer": "Maksaja",
  "widgetReceiver": "Saaja", //
  "widgetOrderType": "Tilaus",
  "widgetNumsLarge": "Tilaukseen sisältyvien numeroiden lukumäärä",
  "widgetNums": "Numerot",
  "widgetInvoicingPhase": "Vaihe",
  "widgetAlreadyPaid": "Maksettu suoritus",
  
  "widgetFixed": "Kesto",
  "widgetPeriod": "Määräa",
  "widgetRecurring": "Toistuvaistilaus",
  "widgetShowMydigi": "Tilauksen tiedot Mydigissä",
  "widgetOrderNo": "Tilausnumero",
  "widgetOrderBenefit": "Tilaajaetu",
  "widgetSalesPerson": "Myyjä",
  "widgetOfferNumber":"Tarjousnumero",
  "widgetArchivingNumber": "Arkistonumero",
  "widgetSaveDate": "Tallennuspäivämäärä",
  "widgetPeriodNumber": "Maksuerät",
  "widgetStart": "Tilaus alku",
  "widgetDeliveryMethod": "Lähetystapa",

  "widgetGroundPost": "Maaposti",
  "widgetAirmail": "Lentoposti",
  "widgetElectric": "Sähköinen",

  "widgetNewNote": "Uusi muistilappu",
  "widgetNote": "Muistilappu",
  "widgetNoteUpdated": "Muistilappu päivitetty",
  "widgetNoteCreated": "Muistilappu tallennettu",
  "widgetNoteCreateFailed": "Muistilapun luonti epäonnistui",
  "widgetNoteUpdateFailed": "Muistilapun päivitys epäonnistui",
  "widgetNoteDescriptionTooLong": "Muistilapun kuvaus liian pitkä. Max 280 merkkiä",
  "widgetNoteMetaTooLong": "Muistilapun meta-tiedot liian pitkät. Max 140 merkkiä",
  "widgetNoteTagsTooLong": "Muistilapun tagit liian pitkät. Max 140 merkkiä",

  "widgetServer": "Asiakaspalvelija",
  "widgetMeta": "Meta",
  "widgetTags": "Tagit",
  "widget":" ",
  " widget": " ",

  "widgetSearchCustomers": "Asiakashaku",
  "widgetMobile": "Matkapuhelin",
  "widgetReferenceNo": "Viitenumero",
  "widgetPusher": "Tyrkyte",

  "widgetSearch": "Hae",
  "widgetSearchHistory": "Hakuhistoria",
  "widgetSearchResults": "Hakutulokset",
  "widgetCustomerLeka": "Leka",
  "widgetCustomerMD": "MyDigi",
  "widgetBackToSearch": "Takaisin hakuun",
  "widgetCustomerInformation": "Asiakastiedot",
  "widgetBirthYear": "Syntymävuosi",
  "widgetItellaTitle": "Itellan postinumerohaku",
  "widgetFonectaTitle": "Fonectan puhelinnumerohaku",
  "widgetOtherPhone": "Matkapuhelin",

  "widgetSalesDenial": "maksuhäiriö",
  "widgetCustomerServiceDenial": "myyntikielto",
  "widgetNoDenial": "Ei kieltoja",

  "widgetPhoneAllowed": "Puhelinmarkkinointi sallittu",
  "widgetEmailAllowed": "Email-markkinointi sallittu",
  "widgetDirectAllowed": "Suoramarkkinointi sallittu",


  "widgetPreviousAddress": "edellistä osoitetta",
  "widgetOnePreviousAddress": "edellinen osoite",
  "widgetAddressHistory": "Osoitehistoria",

  "widgetTempChange": "Väliaikainen",

  "widgetSaveChanges": "Tallenna muutokset?",

  "widgetHousehold": "Talous",
  "widgetMembersWithout": "Talouden jäsenet ilman tilauksia",
  "widgetOrders": "Tilaukset",

  "widgetServiceUse": "Palveluiden käyttö",
  "widgetLastLogin": "Viimeisin kirjautuminen",
  "widgetFirstLogin": "Ensimmäinen kirjautuminen",
  "widgetOffers": "Tarjoukset",
  "widgetShowAllOffers": "Näytä kaikki tarjoukset",

  "widgetNotes": "Muistilaput",
  "widgetExternalServices": "Ulkoiset palvelut",
  "widgetInvoiceArchive": "Laskuarkisto",

  "widgetFb": "Facebook",

  "widgetFI": "Suomi",
  "widgetSE": "Ruotsi",
  "widgetDE": "Saksa",
  "widgetFR": "Ranska",
  "widgetES": "Espanja",

  "widgetCustomerChanged": "Asiakkaan tiedot tallennettu",
  "widgetCustomerNewInfo": "Uudet tiedot tallennettu",

  "widgetService": "Palvelu",

  "widgetEmpty": " ",
  "widgetAK" : "Asiakkaalta kirjeitse",
  "widgetAF": "Asiakkaalta faksitse",
  "widgetAP" : "Asiakkaalta puhelimitse",
  "widgetAS" : "Asiakkaalta sähköpostitse",
  "widgetAT" : "Asiakkaalta verkkopalvelun kautta",
  "widgetLK" : "Lehden keskeytys",
  "widgetLL" : "Lehti lopetettu",
  "widgetMF" : "Myyjältä faksitse",
  "widgetMH" : "Maksuhäiriö",
  "widgetMK" : "Myyjältä kirjeitse",
  "widgetMP" : "Myyjältä puhelimitse",
  "widgetMS" : "Myyjältä sähköpostitse",
  "widgetMT" : "Myyjältä tykillä",
  "widgetMV" : "Myyjältä Voitolla",
  "widgetPA" : "Palveluautomaatilla",
  "widgetPK" : "Palvelukortilla",
  "widgetPP" : "Postin palautus",
  "widgetPT" : "Peruutuksen torjunta",
  "widgetTL" : "Tuote loppu",
  "widgetTP" : "Tekninen peruutus",

  "widget0": "Ei tiedossa",
  "widget1": "Ei ole tilannut",
  "widget2": "Kuollut",
  "widget3": "Sairaus, vanhuus",
  "widget4": "Kaksoistilaus",
  "widget5": "Palveluautomaatin peruutus",
  "widget6": "Maksuvaikeudet",
  "widget7": "Muu syy",
  "widget8": "Postin pal, osoite tuntematon",
  "widget9": "Lehden vaihto/lopetus",
  "widgetL": "Lehden keskeytys",
  "widgetO": "Ei tarjontaa ollenkaan",
  "widgetS": "Lehden siirto",
  "widgetT": "Ei tarjontaa samasta tuotteesta",
  "widgetP": "Peruutuksen torjunta",
  "widgetK": "Ei ota kantaa tarjontaan",
  "widgetX": "Email PT tarjous lähetetty",
  "widgetV": "Vaihto toiseen lehteen",


  "widgetCancelReason": "Syy",
  "widgetDate": "Päivämäärä",
  "widgetChannel": "Kanava",
  "widgetCancelPerson": "Peruja",

  "widgetDenials": "Tarjonnan estot",
  "widgetN" : "ei mitään tarjontaa",
  "widgetOOO": "osoite tuntematon",
  "widgetPPP": "ei puhelintarjontaa",
  "widgetKKK": "ei suoramyyntiä",
  "widgetXXX": "kuollut",
  "widgetAllowed": "ei kieltoja",


  "widgetPaymentMethod": "maksutapa",
  "widgetOrderCard": "kortti",
  "widgetOrderBill": "lasku",

  "widgetSaleDenials": "Myyntikiellot",
  "widgetDataSource": "Lähde",

  "widgetNameTooLongException": "Nimi liian pitkä (Max.26 merkkiä)",
  "widgetStreetTooLongException": "Kadunnimi liian pitkä (Max.26 merkkiä)",
  "widgetSpecifierTooLongException": "Tarkenne liian pitkä (Max.26 merkkiä)",
  "widgetCustomerInfoUpdateFailedException": "Asiakastietojen päivitys epäonnistui",
  "widgetMissingTemporaryDateException": "Tarkista väliaikaisen voimassaolon päivämäärät",

  "secretOrderWarning": "tätä kautta ei voi tilata paketteja",
  "secretOrderRecipientCustomerId": "saajan asiakasnumero",
  "secretOrderAddressId": "oT",
  "secretOrderOfferId": "tarjousnumero",
  "SecretOrderBeginDate": "Tilauksen alkamispäivä (tilaus alkaa kalenterikuun alusta)",
  "secretOrderPayerCustomerId": "Maksajan asiakasnumero",
  "secretOrderProductCode": "Tuote",  
  "secretOrderOrderPrice": "Hinta",
  "secretOrderSalesMethod": "tilauslaji",
  "secretOrderSalesChannel": "tilaustyyppi",
  "secretOrderSubscriberBenefits": "Tilaajaetukoodit (pilkulla eroteltuina)",
  "secretOrderDurationInMonths": "Tilauksen kesto (kk)",
  "OTMandatoryException": "OT on pakollinen",
  "ReceiverMandatoryException": "Saajan asiakasnumero on pakollinen",
  "productCodeMandatory": "Tuotekoodi lisättävä",
  "orderPriceMandatory": "Hinta lisättävä",
  "orderDurationInMonthsMandatory": "Tilauksen kesto kuukausina lisättävä",
  "orderStartDateMandatory": "Tilauksen alkamispäivä valittava",
  "salesChannelAB": "AB - Yhteislaskutettava tilaus",  
  "salesChannelAH": "AH - Henkilökunnan alennustilaus",  
  "salesChannelAM": "AM  - Muu alennustilaus",  
  "salesChannelE": "E - Erikoisverkostot",    
  "salesChannelI": "I - Ilmainen tilaus",  
  "salesChannelIG": "IG - Liiton jäsentilaus ", 
  "salesChannelIK": "IK - Kiinnostuskysely ",   
  "salesChannelIL": "IL - Etuasiakkaan lahjalehdet",      
  "salesChannelIN": "IN - Näytelehdet",         
  "salesChannelIT": "IT - Kentän tilaajaetulehdet ",      
  "salesChannelK": "K - Kenttä ",   
  "salesChannelKS": "KS - Myyjäsuora",
  "salesChannelMD": "MD - MyDigi  ",  
  "salesChannelPT": "PT - Peruutusten torjunta (aspa) ",   
  "salesChannelS": "S - Suora ",    
  "salesChannelSA": "SA - asiakaspalvelu (on-line)",      
  "salesChannelSG": "SG - tekstiviesti (GSM)",  
  "salesChannelSI": "SI - introveloitus",       
  "salesChannelSK": "SK - kuukauden kirja ",    
  "salesChannelSM": "SM - maksusopimus (koonti) ",        
  "salesChannelSN": "SN - interNet",  
  "salesChannelSO": "SO - kerhokaupan osamaksu",
  "salesChannelSP": "SP - palveluautomaatti (puhelin) ",  
  "salesChannelSS": "SS - kerhokauppa",         
  "salesChannelST": "ST - tallennus (kuponki/posti)",     
  "salesChannelV": "V - Vapaakappaletilaus", 
  "salesChannelMandatory": "Tilaustyyppi valittava",
  "cancelDelayedSeason": "Peru tarjousjakson loppuun. Tarjousjakso loppuu ",

  "widgetOrderCancelReasonPeriodEnd": "Jakson loppuun",
  "widgetOrderCancelReasonDate": "Päivämäärä",
  "widgetOrderCancelReasonNow": "Heti",
  "widgetORderCancelReasonFuturePeriodEnd": "Viivästetty",
  "periodLength": "veloituskausi",
  "offerEndDate": "tarjousjakson loppumispäivä",
  "delayedCancelLastValidDate": "Tilauksen viimeinen voimassaolopäivä",
  "cancelAfterPeriods": "jakson jälkeen",
  "widgetUnableToConnectToApi": "Yhteydenotto WebApiin epäonnistui",
  "widgetUnableToConnect": "WebApiin ei saada yhteyttä",

  "widgetOrderCancelText": "Jokaiselle tilausriville pitää asettaa erikseen hinta. Hinta <strong>ei</strong> voi olla tyhjä ja se täytyy laittaa muodossa 0.00 <strong>Huom!</strong> käytä hinnassa erottimena pistettä <strong>.</strong>",
  "widgetOrderCancelQuestion": "Haluatko perua tilauksen?",

  "widgetNoResultsInPeriod": "Ei tuloksia tarkastelujaksolla tai hakuehdoilla.",
  "widgetOrderTime": "Tilausaika",
  "widgetOrderStatus": "Tila",
  "widgetOrderCancelFailed": "Tilauksen peruutus epäonnistui",

  "widgetOrderCancelTypeException": "Peruutuskanava on valittava!",
  "widgetOrderCancelReasonException": "Peruutuksen syy on valittava!",
  "widgetOrderCancelOperationException": "Peruutuksen operaatio on valittava!",

  "widgetRecurringHelpText": "Olet perumassa toistuvaistilausta. Tilaus peruuntuu MyDigiin, eikä Lekaan enää lähetetä uusia tilausjaksoja.",
  "widgetUseEnforceCode": "Käytä pakotuskoodia",
  "widgetSendAccountEmailConfirmation": "Lähetä käyttäjätunnus sähköpostitse",
  "CommaNotApprovedException": "Käytä hinnassa pistettä . ei pilkkua! Esim 1.00",
  "paymentTrouble": "Tilausta ei voida tehdä",
  "paymentTroubleText": "Asiakkaalla on maksuhäiriö, tilausta ei voi tehdä",
  "emailMissing": "Sähköpostiosoite puuttuu",
  "emailMissingText": "Tilausta ei voida tehdä, koska sähköpostiosoitetta ei ole.",
  "asmlService": "Suomen Asiakkuusmarkkinointiliiton kieltopalvelu",
  "widgetStompConfigurationHeader": "Puhelinjärjestelmän konfigurointi",
  "widgetStompConfigurationText": "Alla oleviin numeroihin soitetut puhelut ohjataan avautumaan Konepeltiin",
  "widgetStompUpdateSuccess": "Puhelinjärjestelmän päivitys onnistui",
  "widgetStompUpdateFailed": "Puhelinjärjestelmän päivitys epäonnistui",

  "widgetNoSuchCustomerId": "Asiakasnumeroa ei ole olemassa",
  "widgetCustomerNotInMD": "Asiakas ei ole MyDigissä",
  "widgetCreateMdAccountWithEmail": "Luo asiakkaalle MyDigi-tili antamalla asiakkaan sähköpostiosoite",
  "widgetOrUseExistingEmail" : "Tai käytä olemassa olevaa sähköpostiosoitetta",
  "widgetCustomerEmailMismatch": "Asiakkaan sähköpostiosoitteet eivät vastaa toisiaan MyDigissä ja Lekassa",
  "widgetCreateMD": "Luo tili",
  "widgetUseMailMD": "Käytä tätä",
  "widgetUpdateToThis": "Päivitä tähän",
  "widgetSelectMDaccount": "Valitse käytettävä MyDigi-tili",
  "widgetUpdateLekaEmail": "Päivitä valittu sähköpostiosoite Lekaan",
  "widgetUpdateMDemail": "Päivitä Lekassa oleva sähköposti valittuun MyDigi-tiliin",
  "widgetLastUsed": "Käytetty",
  "widgetCustomerNumberShort": "As.nro",
  "widgetUpdateMDemailFromLeka": "MyDigi-tilin asiakasnumero vaihdetaan Lekan asiakasnumeroon",
  "cardPaymentCantTransfer": "Kortilla maksettua tilausta ei voi siirtää.",
  "widgetUpgradeToMdFailed": "Tilin päivitys MyDigiin epäonnistui",
  "widgetAccountUpgradeSuccess": "Tili päivitetty",
  "widgetAccountUpgraded": "Tilin päivitys MyDigiin onnistui",
  "widgetUpgradeFailedMessage" : "Sähköpostiosoite on jo käytössä tai tapahtui tuntematon virhe. Kokeile toista sähköpostisoitetta",
  "widgetCustomerNumberChangeSuccess" : "Asiakasnumeron siirto onnistui", 
  "widgetCustomerNumberChangeError" : "Asiakasnumeron siirto epäonnistui",
  "widgetChangeEmailSuccess" : "Sähköpostiosoitteen vaihto onnistui",
  "widgetChangeEmailError" : "Sähköpostiosoitteen vaihto epäonnistui",

  "postShipments": "jälkitoimitus",
  "sendEmailOnBreakResume": "Halutaanko jälkitoimituksesta sähköpostihuomautus",
  "uncancelMonthsLimit": "Tilauksen voimaannosto ei ole mahdollista alle 2kk sisään tilausjakson loppumisesta.",
  "cardPaymentCantBreak": "Kortilla maksettua tilausta ei voi keskeyttää.",

  "orderedAt": "Tilattu",
  
  "postShipmentListing": "Tilatut jälkitoimitukset",
  "resendConfirm": "Oletko varma, että haluat lisätä valitut numerot jälkitoimitukseen?",
  "resendSuccess": "Jälkitoimitukseen lisäys onnistui!",
  "resendFailed": "Jälkitoimitukseen lisäys epäonnistui",
  "selectProductName": "Valitse tuote",
  "showOlderIssues": "Näytä vanhempia",
  "postDeliveryOrderIsUrgent": "Lähetetäänkö tilaus pikana",
  "urgentOrder": "Pikatilaus",
  "makeOrder": "Tilaa",
  "issue": "Numero",
  "publishingDate": "Julkaisupäivä",
  "labelDate": "Lipukepäivä",
  "deliveryDate": "Toimituspäivä",
  "printDate": "Painopäivä",
  "productPublishingSchedule": "Tuotteen _PRODUCT_ julkaisuaikataulu"

});
